var GENE01 = [ "GENE01" , {
  outerRadius: -25,
  innerRadius: -10,
  arrow:true,
  arrowGap: 2,
  arrowColor: "blue",
  arrowSize: "12px",
  cdsColor: "blue",
  cdsStrokeColor: "blue",
  cdsStrokeWidth: 5,
  utrWidth: -5,
  utrColor: "blue",
  utrStrokeColor: "blue",
  utrStrokeWidth: 1,
  GENEAnimationDisplay:true,
//  GENEAnimationDirection:"S2E",
  GENEAnimationType:"linear",
  GENEAnimationTime:1000,
  GENEAnimationDelay:50,
} , [
  {chr: "EGFR", strand: "+", start: "57", end: "965", type: "gene", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "57", end: "167", type: "cds", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "185", end: "338", type: "cds", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "361", end: "480", type: "cds", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "505", end: "636", type: "cds", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "713", end: "965", type: "utr", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
]];
