var AUXILIARYLINE01 = [ "AUXILIARYLINE01" , {
     startX: -100,
     startY: 0,
     endX: 100,
     endY: 0,
     AUXILIARYLINEType:"curve",
     AUXILIARYLINEControlPointX:0,
     AUXILIARYLINEControlPointY:-100,
     AUXILIARYLINELineType:"dot",
     AUXILIARYLINEDashArray:4,
     AUXILIARYLINEColor: "black",
     AUXILIARYLINEWidth: 2,
     AUXILIARYLINEMarker:true,
     AUXILIARYLINEMarkerType:"arrow",
     AUXILIARYLINEMarkerColor:"black",
     AUXILIARYLINEMarkerPosition:2,
  }];