var AUXILIARYLINE01 = [ "AUXILIARYLINE01" , {
     startX: -100,
     startY: 200,
     endX: 100,
     endY: 200,
     AUXILIARYLINEType:"curve",
     AUXILIARYLINEControlPointX:0,
     AUXILIARYLINEControlPointY:100,
     AUXILIARYLINELineType:"dot",
     AUXILIARYLINEDashArray:4,
     AUXILIARYLINEColor: "black",
     AUXILIARYLINEWidth: 2,
     AUXILIARYLINEMarker:true,
     AUXILIARYLINEMarkerType:"arrow",
     AUXILIARYLINEMarkerColor:"black",
     AUXILIARYLINEMarkerPosition:2,
  }];

var AUXILIARYLINE02 = [ "AUXILIARYLINE02" , {
      startX: -100,
      startY: 100,
      endX: 100,
      endY: 100,
      AUXILIARYLINEType:"broken",
      AUXILIARYLINEControlPointX:0,
      AUXILIARYLINEControlPointY:50,
      AUXILIARYLINELineType:"solid",
      AUXILIARYLINEDashArray:4,
      AUXILIARYLINEColor: "red",
      AUXILIARYLINEWidth: 2,
      AUXILIARYLINEMarker:true,
      AUXILIARYLINEMarkerType:"stub",
      AUXILIARYLINEMarkerColor:"black",
      AUXILIARYLINEMarkerPosition:3,
  }];

var AUXILIARYLINE03 = [ "AUXILIARYLINE03" , {
      startX: -100,
      startY: 0,
      endX: 100,
      endY: 0,
      AUXILIARYLINEType:"straight",
      AUXILIARYLINEControlPointX:0,
      AUXILIARYLINEControlPointY:-50,
      AUXILIARYLINELineType:"dot",
      AUXILIARYLINEDashArray:4,
      AUXILIARYLINEColor: "blue",
      AUXILIARYLINEWidth: 2,
      AUXILIARYLINEMarker:true,
      AUXILIARYLINEMarkerType:"square",
      AUXILIARYLINEMarkerColor:"green",
      AUXILIARYLINEMarkerPosition:2,
  }];

var AUXILIARYLINE04 = [ "AUXILIARYLINE04" , {
      startX: -100,
      startY: -100,
      endX: 100,
      endY: -100,
      AUXILIARYLINEType:"curve",
      AUXILIARYLINEControlPointX:0,
      AUXILIARYLINEControlPointY:-50,
      AUXILIARYLINELineType:"solid",
      AUXILIARYLINEDashArray:4,
      AUXILIARYLINEColor: "black",
      AUXILIARYLINEWidth: 2,
      AUXILIARYLINEMarker:true,
      AUXILIARYLINEMarkerType:"circle",
      AUXILIARYLINEMarkerColor:"black",
      AUXILIARYLINEMarkerPosition:1,
  }];

var AUXILIARYLINE05 = [ "AUXILIARYLINE05" , {
  startX: -100,
  startY: -150,
  endX: 100,
  endY: -150,
  AUXILIARYLINEType:"broken",
  AUXILIARYLINEControlPointX:0,
  AUXILIARYLINEControlPointY:-200,
  AUXILIARYLINELineType:"dot",
  AUXILIARYLINEDashArray:8,
  AUXILIARYLINEColor: "orange",
  AUXILIARYLINEWidth: 2,
  AUXILIARYLINEMarker:true,
  AUXILIARYLINEMarkerType:"circle",
  AUXILIARYLINEMarkerColor:"black",
  AUXILIARYLINEMarkerPosition:0,
  }];

