var LEGEND01 = [ "LEGEND01" , {
  x: -50,
  y: -230,
  title: " ",
  titleSize: 16,
  titleWeight: "bold",
  GapBetweenGraphicText:5,
  GapBetweenLines:20
  } , [
    {type: "circle", color:"#1E77B4",opacity:"1.0",circleSize:"8",text: "C.CK", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#AEC7E8",opacity:"1.0",circleSize:"8",text: "C.NPK", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#FF7F0B",opacity:"1.0",circleSize:"8",text: "GC.CK", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#FFBB78",opacity:"1.0",circleSize:"8",text: "GC.NPK", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#2AA02B",opacity:"1.0",circleSize:"8",text: "Alphaproteobacteria", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#98DF8A",opacity:"1.0",circleSize:"8",text: "Betaproteobacteria", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#D62628",opacity:"1.0",circleSize:"8",text: "Gammaproteobacteria", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#FF9896",opacity:"1.0",circleSize:"8",text: "Deltaproteobacteria", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#9467BD",opacity:"1.0",circleSize:"8",text: "Acidobacteria", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#C5B0D5",opacity:"1.0",circleSize:"8",text: "Actinobacteria", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#8C564C",opacity:"1.0",circleSize:"8",text: "Bacteroidetes", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#C49C94",opacity:"1.0",circleSize:"8",text: "Chloroflexi", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#E377C2",opacity:"1.0",circleSize:"8",text: "Firmicutes", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#F7B6D2",opacity:"1.0",circleSize:"8",text: "Gemmatimonadetes", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#7F7F7F",opacity:"1.0",circleSize:"8",text: "Planctomycetes", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#C7C7C7",opacity:"1.0",circleSize:"8",text: "Thaumarchaeota", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#BCBC22",opacity:"1.0",circleSize:"8",text: "Verrucomicrobia", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#DADB8D",opacity:"1.0",circleSize:"8",text: "Ascomycota", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#19BDCF",opacity:"1.0",circleSize:"8",text: "Basidiomycota", textSize: "14",textWeight:"normal"},
    {type: "circle", color:"#9ED9E5",opacity:"1.0",circleSize:"8",text: "Zygomycota", textSize: "14",textWeight:"normal"},
  ]];
