var GENE01 = [ "GENE01" , {
  outerRadius: -25,
  innerRadius: -10,
  arrow:true,
  arrowGap: 8,
  arrowColor: "black",
  arrowSize: "12px",
  cdsColor: "#1e77b3",
  cdsStrokeColor: "#1e77b3",
  cdsStrokeWidth: 5,
  utrWidth: -2,
  utrColor: "#fe7f0e",
  utrStrokeColor: "#fe7f0e",
  utrStrokeWidth: 1,
  GENEAnimationDisplay:true,
//  GENEAnimationDirection:"S2E",
  GENEAnimationType:"linear",
  GENEAnimationTime:1000,
  GENEAnimationDelay:50,
} , [
  {chr: "EGFR", strand: "+", start: "57", end: "360", type: "gene", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "57", end: "80", type: "utr", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "80", end: "167", type: "cds", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "195", end: "250", type: "cds", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "280", end: "340", type: "cds", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "342", end: "360", type: "utr", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "457", end: "860", type: "gene", name: "EGFR2", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "457", end: "470", type: "utr", name: "EGFR2", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "470", end: "536", type: "cds", name: "EGFR2", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "580", end: "680", type: "cds", name: "EGFR2", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "700", end: "730", type: "cds", name: "EGFR2", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "750", end: "770", type: "cds", name: "EGFR2", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "820", end: "850", type: "cds", name: "EGFR2", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "852", end: "860", type: "utr", name: "EGFR2", link: "https://www.intogen.org/search?gene=EGFR"},
]];

var GENE02 = [ "GENE02" , {
  outerRadius: -75,
  innerRadius: -60,
  arrow:true,
  arrowGap: 10,
  arrowColor: "black",
  arrowSize: "12px",
  cdsColor: "#1e77b3",
  cdsStrokeColor: "#1e77b3",
  cdsStrokeWidth: 5,
  utrWidth: -2,
  utrColor: "#fe7f0e",
  utrStrokeColor: "#fe7f0e",
  utrStrokeWidth: 1,
  GENEAnimationDisplay:true,
//  GENEAnimationDirection:"S2E",
  GENEAnimationType:"linear",
  GENEAnimationTime:1000,
  GENEAnimationDelay:50,
} , [
  {chr: "EGFR", strand: "-", start: "1", end: "250", type: "gene", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "-", start: "1", end: "30", type: "utr", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "-", start: "30", end: "80", type: "cds", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "-", start: "110", end: "150", type: "cds", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "-", start: "190", end: "230", type: "cds", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "-", start: "232", end: "250", type: "utr", name: "EGFR", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "400", end: "550", type: "gene", name: "EGFR2", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "400", end: "430", type: "utr", name: "EGFR2", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "430", end: "450", type: "cds", name: "EGFR2", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "460", end: "490", type: "cds", name: "EGFR2", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "520", end: "540", type: "cds", name: "EGFR2", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "+", start: "542", end: "550", type: "utr", name: "EGFR2", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "-", start: "800", end: "950", type: "gene", name: "EGFR3", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "-", start: "800", end: "810", type: "utr", name: "EGFR3", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "-", start: "810", end: "830", type: "cds", name: "EGFR3", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "-", start: "850", end: "880", type: "cds", name: "EGFR3", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "-", start: "920", end: "935", type: "cds", name: "EGFR3", link: "https://www.intogen.org/search?gene=EGFR"},
  {chr: "EGFR", strand: "-", start: "935", end: "950", type: "utr", name: "EGFR3", link: "https://www.intogen.org/search?gene=EGFR"},
]];


